<?php

/**
 * Handles all operations for the Expercash API
 *
 * @link       http://www.kamenew.com
 * @since      1.4.0
 *
 * @package    Smartkwk
 * @subpackage Smartkwk/admin
 * @author     Artur Kamenew <artur@kamenew.com>
 */
class Smartkwk_Expercash {

    /**
     * Get transactions of the last 30 days (default).
     * @since    1.4.0
     * @access   private
     * @var int $_date_range Number of days
     */
    private $_date_range = 30;

    /**
     * Filepath where the ruby script writes the file
     * @since    1.4.0
     * @access   private
     * @var string $_generated_filepath Filepath
     */
    private $_generated_filepath = SMARTKWK_PLUGIN_DIR . 'admin/external/valid_transactions.csv';

    /**
     * Filepath where the file was uploaded to
     * @since    1.4.0
     * @access   private
     * @var string $_uploaded_filepath Filepath
     */
    private $_uploaded_filepath;

    /**
     * Get date range
     * @return int
     */
    function get_date_range() {
        return $this->_date_range;
    }

    /**
     * Get filepath of generated file
     * @return string
     */
    function get_generated_filepath() {
        return $this->_generated_filepath;
    }

    /**
     * Get filepath of uploaded file
     * @return string
     */
    function get_uploaded_filepath() {
        return $this->_uploaded_filepath;
    }

    /**
     * Set date range
     * @param int $_date_range
     */
    function set_date_range($_date_range) {
        $this->_date_range = $_date_range;
    }

    /**
     * Set the filepath of where the generated file will be written
     * @param type $_generated_filepath
     */
    function set_generated_filepath($_generated_filepath) {
        $this->_generated_filepath = $_generated_filepath;
    }

    /**
     * Set the filepath of where the uploaded file was saved
     * @param type $_uploaded_filepath
     */
    function set_uploaded_filepath($_uploaded_filepath) {
        $this->_uploaded_filepath = $_uploaded_filepath;
    }

    /**
     * Get data from Expercash API and write it to a file
     *
     * @since    1.4.0
     * @param string $username Expercash API Username
     * @param string $password Expercash API Password
     * @throws Exception
     */
    public function generate_expercash_file($username, $password) {

        if (trim($username) === '' || trim($password) === '') {
            throw new Exception('Username and password must be set.');
        }

        //file where the data will be written into
        $targetFile = $this->get_generated_file();

        @unlink($targetFile); //delete previous file

        $dateRange = date('d m Y', strtotime("-{$this->_date_range} days")) . ' ' . date('d m Y');

        // Change directory
        chdir(SMARTKWK_PLUGIN_DIR . '/admin/external');

        $cmd = "ruby expercash.rb $username $password $dateRange";

        //execute command and generate file
        system($cmd);

        //verify that file has been written
        if (!file_exists($targetFile)) {
            throw new Exception('File could not be generated.');
        }
    }

    /**
     * Import the Expercash data generated by ruby script
     *
     * @since    1.4.0
     * @return int Number of imported rows
     */
    public function import_generated_expercash_file() {

        $targetFile = $this->get_generated_filepath();

        if (!file_exists($targetFile)) {
            throw new Exception("File {$targetFile} does not exist.");
        }

        //import targetfile
        $file = fopen($targetFile, "r");

        global $wpdb;
        $updated = 0;
        while (($row = fgetcsv($file, 0, ';'))) {

            $businessCaseNumber = $row[1];

            //update by business_case
            $ok = $wpdb->update($wpdb->prefix . 'smart_kwk', array('paid' => 1), array('business_case' => $businessCaseNumber));
            if ($ok) {
                $updated++;
            }
        }

        fclose($file);

        return $updated;
    }

    /**
     * Import Expercash file from upload
     * @since    1.4.0
     * @global type $wpdb
     * @return int
     */
    public function import_uploaded_expercash_file() {

        $filepath = $this->get_uploaded_filepath();

        if (!file_exists($filepath)) {
            throw new Exception('Uploaded file not found.');
        }

        $file = fopen($filepath, "r");

        global $wpdb;
        $updated = 0;
        while (($row = fgetcsv($file, 0, ';'))) {

            if (stripos(trim($row[5]), 'Referenz') !== false) {
                continue; //skip header row
            }

            $businessCaseNumber = trim($row[5]);

            //update by business_case (alternatively by referral id)
            $ok = $wpdb->update($wpdb->prefix . 'smart_kwk', array('paid' => 1), array('business_case' => $businessCaseNumber));
            if ($ok) {
                $updated++;
            }
        }

        fclose($file);
        @unlink($filepath);

        return $updated;
    }

}
